--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Jorgebyte/AntiBugPing
build-by-default: true
branches:
- main
projects:
  AntiBugPing:
    path: ""
    lint:
      phpstan: false
    icon: Icon.png
...
