name: AntiBugPing
author: Jorgebyte
version: 1.1.0
api: 5.0.0
main: Jorgebyte\AntiBugPing\Main

permissions:
  antibugping.bypass:
    default: op
    description: Full bypass of AntiBugPing mitigations
  antibugping.notify:
    default: op
    description: Receive AntiBugPing mitigation alerts
